/* SPDX-FileCopyrightText: 2026 LichtFeld Studio Authors
 * SPDX-License-Identifier: GPL-3.0-or-later */

// Build-time post-processing for the compiled tensor compute modules.
//
//   spirv_finalize <input.spv> <output.spv> <manifest.json>
//   spirv_finalize embed <table.cpp> <name> <finalized.spv> [<name> <finalized.spv> ...]
//
// Every float width declares SignedZeroInfNanPreserve. Manifest facts come
// from the finalized binary.

#include "../spirv_module.hpp"

#include <algorithm>
#include <array>
#include <cctype>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <map>
#include <optional>
#include <set>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace {
    using namespace lfs::core::internal::spirv;
    [[noreturn]] void fail(const std::string& message) { throw std::runtime_error(message); }
    std::vector<uint32_t> read_words(const char* path) {
        std::ifstream stream(path, std::ios::binary | std::ios::ate);
        if (!stream) {
            fail(std::string("cannot open ") + path);
        }
        const std::streamoff bytes = stream.tellg();
        if (bytes < 20 || bytes % 4 != 0) {
            fail(std::string("not a SPIR-V module: ") + path);
        }
        std::vector<uint32_t> words(static_cast<size_t>(bytes) / 4);
        stream.seekg(0);
        stream.read(reinterpret_cast<char*>(words.data()), bytes);
        if (!stream || words[0] != spv::MagicNumber) {
            fail(std::string("not a SPIR-V module: ") + path);
        }
        return words;
    }

    std::string capability_name(const spv::Capability capability) {
        const std::string name = spv::CapabilityToString(capability);
        return name == "Unknown" ? "Capability" + std::to_string(static_cast<uint32_t>(capability)) : name;
    }

    std::string json_string_list(const std::vector<std::string>& items) {
        std::string text = "[";
        for (size_t index = 0; index < items.size(); ++index) {
            text += (index == 0 ? "\"" : ", \"") + items[index] + "\"";
        }
        return text + "]";
    }

    template <typename Range>
    std::string json_number_list(const Range& items) {
        std::string text = "[";
        bool first = true;
        for (const auto item : items) {
            text += (first ? "" : ", ") + std::to_string(item);
            first = false;
        }
        return text + "]";
    }

    void write_manifest(const char* path, const Module& module, const Analysis& analysis) {
        std::vector<std::string> capabilities;
        for (const spv::Capability capability : analysis.capabilities) {
            capabilities.push_back(capability_name(capability));
        }
        const uint32_t version = module.header[1];
        std::ofstream stream(path, std::ios::binary | std::ios::trunc);
        stream << "{\n"
               << "  \"entry_point\": \"" << analysis.entry_name << "\",\n"
               << "  \"execution_model\": \"GLCompute\",\n"
               << "  \"local_size\": " << json_number_list(analysis.local_size) << ",\n"
               << "  \"push_constant_size\": " << analysis.push_constant_size << ",\n"
               << "  \"capabilities\": " << json_string_list(capabilities) << ",\n"
               << "  \"extensions\": " << json_string_list(analysis.extensions) << ",\n"
               << "  \"float_widths\": " << json_number_list(analysis.float_widths) << ",\n"
               << "  \"signed_zero_inf_nan_preserve\": " << json_number_list(analysis.preserve_widths) << ",\n"
               << "  \"spirv_version\": \"" << ((version >> 16) & 0xFFu) << "." << ((version >> 8) & 0xFFu)
               << "\"\n"
               << "}\n";
        if (!stream) {
            fail(std::string("cannot write ") + path);
        }
    }

    std::string identifier(const std::string_view name) {
        std::string text(name);
        for (char& character : text) {
            if (!std::isalnum(static_cast<unsigned char>(character))) {
                character = '_';
            }
        }
        return text;
    }

    // Writes one translation unit holding every module and its loader facts, so
    // the library carries its shaders instead of reading them from a build-tree
    // path at run time.
    void write_table(const char* path, const std::vector<std::pair<std::string, std::string>>& modules) {
        std::ofstream stream(path, std::ios::binary | std::ios::trunc);
        stream << "// Generated by lfs_tensor_spirv_finalize from the finalized SPIR-V modules; do not edit.\n"
               << "#include \"core/tensor/backend/vulkan/vk_shader_table.hpp\"\n\n"
               << "#include <algorithm>\n\n"
               << "namespace lfs::core::internal {\n    namespace {\n";
        std::vector<std::string> names;
        for (const auto& [name, file] : modules) {
            const std::vector<uint32_t> words = read_words(file.c_str());
            const Module module = parse(words);
            const Analysis analysis = analyze(module);
            for (const uint32_t width : analysis.float_widths) {
                if (!analysis.preserve_widths.contains(width)) {
                    fail(name + " is not finalized: SignedZeroInfNanPreserve " + std::to_string(width) + " missing");
                }
            }
            const std::string id = identifier(name);
            names.push_back(name);
            stream << "        const std::array<uint32_t, " << words.size() << "> kWords_" << id << "{";
            for (size_t index = 0; index < words.size(); ++index) {
                if (index % 8 == 0) {
                    stream << "\n           ";
                }
                char text[16];
                std::snprintf(text, sizeof(text), " 0x%08xu,", words[index]);
                stream << text;
            }
            stream << "\n        };\n";
            stream << "        constexpr std::array<std::string_view, " << analysis.capabilities.size()
                   << "> kCapabilities_" << id << "{";
            for (size_t index = 0; index < analysis.capabilities.size(); ++index) {
                stream << (index == 0 ? "\"" : ", \"") << capability_name(analysis.capabilities[index]) << "\"";
            }
            stream << "};\n";
            const auto widths = [&](const char* label, const std::set<uint32_t>& values) {
                stream << "        constexpr std::array<uint32_t, " << values.size() << "> k" << label << "_" << id
                       << "{";
                bool first = true;
                for (const uint32_t value : values) {
                    stream << (first ? "" : ", ") << value << "u";
                    first = false;
                }
                stream << "};\n";
            };
            widths("FloatWidths", analysis.float_widths);
            widths("Preserve", analysis.preserve_widths);
            stream << "        const EmbeddedShader kShader_" << id << "{\n"
                   << "            \"" << name << "\", kWords_" << id << ", \"" << analysis.entry_name << "\",\n"
                   << "            {" << analysis.local_size[0] << "u, " << analysis.local_size[1] << "u, "
                   << analysis.local_size[2] << "u}, " << analysis.push_constant_size << "u,\n"
                   << "            kCapabilities_" << id << ", kFloatWidths_" << id << ", kPreserve_" << id << "};\n\n";
        }
        stream << "        const std::array<EmbeddedShader, " << names.size() << "> kShaders{";
        for (size_t index = 0; index < names.size(); ++index) {
            stream << (index == 0 ? "" : ",") << "\n            kShader_" << identifier(names[index]);
        }
        stream << "};\n    } // namespace\n\n"
               << "    std::span<const EmbeddedShader> embedded_shaders() {\n"
               << "        return kShaders;\n    }\n\n"
               << "    const EmbeddedShader* find_embedded_shader(const std::string_view name) {\n"
               << "        const auto iterator = std::ranges::find(kShaders, name, &EmbeddedShader::name);\n"
               << "        return iterator == kShaders.end() ? nullptr : &*iterator;\n    }\n\n"
               << "} // namespace lfs::core::internal\n";
        if (!stream) {
            fail(std::string("cannot write ") + path);
        }
    }

    int run(const int argc, char** const argv) {
        if (argc >= 5 && std::string_view(argv[1]) == "embed") {
            if ((argc - 3) % 2 != 0) {
                std::fprintf(stderr, "usage: %s embed <table.cpp> <name> <finalized.spv> ...\n", argv[0]);
                return 2;
            }
            std::vector<std::pair<std::string, std::string>> modules;
            for (int index = 3; index + 1 < argc; index += 2) {
                modules.emplace_back(argv[index], argv[index + 1]);
            }
            write_table(argv[2], modules);
            return 0;
        }
        if (argc != 4) {
            std::fprintf(stderr, "usage: %s <input.spv> <output.spv> <manifest.json>\n", argv[0]);
            return 2;
        }
        const auto words = finalize(read_words(argv[1]));
        const auto module = parse(words);
        const auto finished = analyze(module);
        std::ofstream output(argv[2], std::ios::binary | std::ios::trunc);
        output.write(reinterpret_cast<const char*>(words.data()),
                     static_cast<std::streamsize>(words.size() * sizeof(uint32_t)));
        if (!output) {
            fail(std::string("cannot write ") + argv[2]);
        }
        write_manifest(argv[3], module, finished);
        return 0;
    }

} // namespace

int main(const int argc, char** const argv) {
    try {
        return run(argc, argv);
    } catch (const std::exception& error) {
        // LFS-CENSUS-OK(empty-catch): build-time host tool; the failure goes to
        // stderr and the non-zero exit fails the build.
        std::fprintf(stderr, "spirv_finalize: %s: %s\n", argc > 1 ? argv[1] : "", error.what());
        return 1;
    }
}
