"""Geometry node trees and modifiers"""

from collections.abc import Sequence
from typing import overload

import lichtfeld


class Splats:
    def __init__(self, means: lichtfeld.Tensor, sh0: lichtfeld.Tensor, shN: lichtfeld.Tensor, scaling: lichtfeld.Tensor, rotation: lichtfeld.Tensor, opacity: lichtfeld.Tensor, sh_degree: int = 0, scene_scale: float = 1.0) -> None: ...

    @property
    def means(self) -> lichtfeld.Tensor: ...

    @property
    def sh0(self) -> lichtfeld.Tensor: ...

    @property
    def shN(self) -> lichtfeld.Tensor: ...

    @property
    def scaling(self) -> lichtfeld.Tensor: ...

    @property
    def rotation(self) -> lichtfeld.Tensor: ...

    @property
    def opacity(self) -> lichtfeld.Tensor: ...

    def replace(self, **kwargs) -> Splats: ...

class Points:
    def __init__(self, positions: lichtfeld.Tensor, colors: lichtfeld.Tensor) -> None: ...

    @property
    def positions(self) -> lichtfeld.Tensor: ...

    @property
    def colors(self) -> lichtfeld.Tensor: ...

    def replace(self, **kwargs) -> Points: ...

class Mesh:
    @property
    def vertices(self) -> lichtfeld.Tensor: ...

    @property
    def indices(self) -> lichtfeld.Tensor: ...

    def replace(self, **kwargs) -> Mesh: ...

class Geometry:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, splats: Splats | None = None, points: Points | None = None, mesh: Mesh | None = None) -> None: ...

    @property
    def splats(self) -> Splats | None: ...

    @property
    def points(self) -> Points | None: ...

    @property
    def mesh(self) -> Mesh | None: ...

    @property
    def empty(self) -> bool: ...

    def replace(self, **kwargs) -> Geometry: ...

class Input:
    def __init__(self, identifier: str, type: str, default: object | None = None, min: float | None = None, max: float | None = None, field: bool = False, description: str = '') -> None: ...

class Output:
    def __init__(self, identifier: str, type: str, description: str = '') -> None: ...

class Property:
    def __init__(self, identifier: str, type: str, default: object | None = None, items: Sequence[str] = [], description: str = '') -> None: ...

class Node:
    def __init__(self) -> None: ...

class NodeContext:
    def input(self, arg: str, /) -> object: ...

    @overload
    def field(self, arg0: str, arg1: Geometry, /) -> lichtfeld.Tensor: ...

    @overload
    def field(self, arg0: str, arg1: Splats, /) -> lichtfeld.Tensor: ...

    @overload
    def field(self, arg0: str, arg1: Points, /) -> lichtfeld.Tensor: ...

    @overload
    def field(self, arg0: str, arg1: Mesh, /) -> lichtfeld.Tensor: ...

    def prop(self, arg: str, /) -> object: ...

    def output(self, arg0: str, arg1: object, /) -> None: ...

class NodeHandle:
    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

    def keyframe_insert(self, input: str, time: float | None = None, value: object | None = None, easing: int = 0) -> None: ...

    def keyframe_remove(self, input: str, time: float | None = None) -> bool: ...

    @property
    def type_id(self) -> str: ...

    @property
    def location(self) -> list[float]: ...

    @location.setter
    def location(self, arg: Sequence[float], /) -> None: ...

    @property
    def muted(self) -> bool: ...

    @muted.setter
    def muted(self, arg: bool, /) -> None: ...

    @property
    def graph(self) -> NodeTree | None: ...

    @graph.setter
    def graph(self, arg: NodeTree, /) -> None: ...

    def set_input(self, arg0: str, arg1: object, /) -> None: ...

    def get_input(self, arg: str, /) -> object: ...

    def set_property(self, arg0: str, arg1: object, /) -> None: ...

    def get_property(self, arg: str, /) -> object: ...

    @property
    def error(self) -> str | None: ...

    @property
    def eval_time_ms(self) -> float: ...

class TreeInterface:
    def add_input(self, type: str, label: str, default: object | None = None, min: float | None = None, max: float | None = None, step: float | None = None) -> str: ...

    def add_output(self, type: str, label: str, default: object | None = None, min: float | None = None, max: float | None = None, step: float | None = None) -> str: ...

    def remove(self, arg0: str, arg1: str, /) -> None: ...

    def move(self, arg0: str, arg1: str, arg2: int, /) -> None: ...

class NodeTree:
    @property
    def uuid(self) -> str: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

    @property
    def nodes(self) -> list[NodeHandle]: ...

    @property
    def input_node(self) -> NodeHandle: ...

    @property
    def output_node(self) -> NodeHandle: ...

    @property
    def interface(self) -> TreeInterface: ...

    def add_node(self, type_id: str, name: str = '', location: Sequence[float] = [0.0, 0.0]) -> NodeHandle: ...

    def remove_node(self, arg: str, /) -> bool: ...

    def link(self, arg0: NodeHandle, arg1: str, arg2: NodeHandle, arg3: str, /) -> None: ...

    def unlink(self, arg0: NodeHandle, arg1: str, arg2: NodeHandle, arg3: str, /) -> bool: ...

    def copy(self, arg: Sequence[NodeHandle], /) -> str: ...

    def paste(self, text: str, location: Sequence[float] | None = None) -> list[NodeHandle]: ...

    def make_group(self, nodes: Sequence[NodeHandle], name: str | None = None) -> NodeHandle: ...

    def ungroup(self, arg: NodeHandle, /) -> None: ...

    def add_input(self, identifier: str, type: str, default: object | None = None, min: float | None = None, max: float | None = None) -> None: ...

    def to_json(self) -> str: ...

class Modifier:
    @property
    def name(self) -> str: ...

    @property
    def enabled(self) -> bool: ...

    @enabled.setter
    def enabled(self, arg: bool, /) -> None: ...

    @property
    def show_viewport(self) -> bool: ...

    @show_viewport.setter
    def show_viewport(self, arg: bool, /) -> None: ...

    def set_input(self, arg0: str, arg1: object, /) -> None: ...

    def capture_selection(self, arg: str, /) -> None: ...

def node_types() -> list: ...

def new_tree(name: str = 'Node Graph') -> NodeTree: ...

def get_tree(arg: str, /) -> NodeTree | None: ...

def trees() -> list[NodeTree]: ...

def remove_tree(arg: str, /) -> bool: ...

def load_tree(arg: str, /) -> NodeTree: ...

def link(arg0: NodeTree, arg1: NodeHandle, arg2: str, arg3: NodeHandle, arg4: str, /) -> None: ...

def unlink(arg0: NodeTree, arg1: NodeHandle, arg2: str, arg3: NodeHandle, arg4: str, /) -> bool: ...

def evaluate_tree(tree: NodeTree, geometry: Geometry, time: float | None = None, device: str | None = None) -> Geometry: ...

def register_node(arg: object, /) -> str: ...

def unregister_node(arg: str, /) -> bool: ...

def unregister_nodes_for_module(arg: str, /) -> int: ...

def add_modifier(node_name: str, tree: NodeTree, name: str = '') -> Modifier: ...

def templates() -> object: ...

def apply_template(target: str, id: str, name: str = '') -> Modifier: ...

def save_template(tree: NodeTree, name: str, description: str, category: str) -> str: ...

def delete_template(id: str) -> bool: ...

def rename_template(id: str, name: str) -> bool: ...

def import_template(path: str) -> str: ...

def export_template(id: str, path: str) -> bool: ...

def preview(target: str, node: str, socket: str | None = None) -> None: ...

def clear_preview() -> None: ...

def modifiers(arg: str, /) -> list[Modifier]: ...

def remove_modifier(arg0: str, arg1: str, /) -> bool: ...

def move_modifier(arg0: str, arg1: str, arg2: int, /) -> bool: ...

def performance(reset: bool = False) -> object: ...

def profile(enabled: bool) -> None:
    """
    Include each node's device work in its time; each node then waits for the GPU.
    """

def evaluate(arg: str, /) -> dict: ...

def evaluated(arg: str, /) -> Geometry | None: ...

def apply_modifier(arg0: str, arg1: str, /) -> None: ...
