from typing import Any, Optional
from lichtfeld import Tensor

class Splats:
    def __init__(self, means: Tensor, sh0: Tensor, shN: Tensor, scaling: Tensor,
                 rotation: Tensor, opacity: Tensor, sh_degree: int = 0,
                 scene_scale: float = 1.0) -> None: ...
    means: Tensor
    sh0: Tensor
    shN: Tensor
    scaling: Tensor
    rotation: Tensor
    opacity: Tensor
    def replace(self, **values: Any) -> Splats: ...

class Points:
    def __init__(self, positions: Tensor, colors: Tensor) -> None: ...
    positions: Tensor
    colors: Tensor
    def replace(self, **values: Any) -> Points: ...

class Mesh:
    vertices: Tensor
    indices: Tensor
    def replace(self, **values: Any) -> Mesh: ...

class Geometry:
    def __init__(self, splats: Optional[Splats] = None,
                 points: Optional[Points] = None,
                 mesh: Optional[Mesh] = None) -> None: ...
    splats: Optional[Splats]
    points: Optional[Points]
    mesh: Optional[Mesh]
    empty: bool
    def replace(self, **values: Any) -> Geometry: ...

class Input:
    def __init__(self, identifier: str, type: str, default: Any = None,
                 min: Optional[float] = None, max: Optional[float] = None,
                 field: bool = False, description: str = "") -> None: ...

class Output:
    def __init__(self, identifier: str, type: str, description: str = "") -> None: ...

class Property:
    def __init__(self, identifier: str, type: str, default: Any = None,
                 items: list[str] = [], description: str = "") -> None: ...

class NodeContext:
    def input(self, identifier: str) -> Any: ...
    def field(self, identifier: str, domain: Splats | Points | Mesh) -> Tensor: ...
    def prop(self, identifier: str) -> Any: ...
    def output(self, identifier: str, value: Any) -> None: ...

class Node:
    id: str
    label: str
    category: str
    description: str
    help: str
    inputs: list[Input]
    outputs: list[Output]
    properties: list[Property]
    def execute(self, ctx: NodeContext) -> Optional[dict[str, Any] | Geometry]: ...

class NodeHandle:
    name: str
    type_id: str
    location: tuple[float, float]
    muted: bool
    error: Optional[str]
    eval_time_ms: float
    def set_input(self, name: str, value: Any) -> None: ...
    def get_input(self, name: str) -> Any: ...
    def set_property(self, name: str, value: Any) -> None: ...
    def get_property(self, name: str) -> Any: ...

class NodeTree:
    uuid: str
    name: str
    nodes: list[NodeHandle]
    input_node: NodeHandle
    output_node: NodeHandle
    def add_node(self, type_id: str, name: str = "",
                 location: tuple[float, float] = (0.0, 0.0)) -> NodeHandle: ...
    def remove_node(self, name: str) -> bool: ...
    def link(self, from_node: NodeHandle, output: str, to_node: NodeHandle,
             input: str) -> None: ...
    def unlink(self, from_node: NodeHandle, output: str, to_node: NodeHandle,
               input: str) -> bool: ...
    def add_input(self, identifier: str, type: str, default: Any = None,
                  min: Optional[float] = None,
                  max: Optional[float] = None) -> None: ...
    def to_json(self) -> str: ...

class Modifier:
    name: str
    enabled: bool
    show_viewport: bool
    def set_input(self, name: str, value: Any) -> None: ...
    def capture_selection(self, node_name: str) -> None: ...

def node_types() -> list[dict[str, Any]]: ...
def new_tree(name: str = "Node Graph") -> NodeTree: ...
def get_tree(name_or_uuid: str) -> Optional[NodeTree]: ...
def trees() -> list[NodeTree]: ...
def remove_tree(name_or_uuid: str) -> bool: ...
def load_tree(json_text: str) -> NodeTree: ...
def link(tree: NodeTree, from_node: NodeHandle, output: str,
         to_node: NodeHandle, input: str) -> None: ...
def unlink(tree: NodeTree, from_node: NodeHandle, output: str,
           to_node: NodeHandle, input: str) -> bool: ...
def evaluate_tree(tree: NodeTree, geometry: Geometry) -> Geometry: ...
def register_node(cls: type[Node]) -> str: ...
def unregister_node(id: str) -> bool: ...
def unregister_nodes_for_module(prefix: str) -> int: ...
def add_modifier(node_name: str, tree: NodeTree, name: str = "") -> Modifier: ...
def remove_modifier(node_name: str, name: str) -> bool: ...
def move_modifier(node_name: str, name: str, index: int) -> bool: ...
def modifiers(node_name: str) -> list[Modifier]: ...
def evaluate(node_name: str) -> dict[str, Any]: ...
def performance(reset: bool = False) -> dict[str, Any]:
    """Worker counters and optional CPU frame timings; reset starts a measurement window."""
    ...
def evaluated(node_name: str) -> Optional[Geometry]: ...
def apply_modifier(node_name: str, name: str) -> None: ...
