/* SPDX-FileCopyrightText: 2026 LichtFeld Studio Authors
 * SPDX-License-Identifier: GPL-3.0-or-later */
#include "internal/tensor_functors.hpp"
#include <cuda_fp16.h>
namespace ops = lfs::core::ops;
using uint = unsigned int;
#define EXPR(name, expression)                                                              \
    extern "C" __device__ __noinline__ uint expr_##name(uint a, uint b, uint c) {           \
        const float x = __uint_as_float(a), y = __uint_as_float(b), z = __uint_as_float(c); \
        return (expression);                                                                \
    }
EXPR(Abs, __float_as_uint(ops::abs_op{}(x)))
EXPR(Neg, __float_as_uint(ops::neg_op{}(x)))
EXPR(Exp, __float_as_uint(ops::exp_op{}(x)))
EXPR(Log, __float_as_uint(ops::log_op{}(x)))
EXPR(Sqrt, __float_as_uint(ops::sqrt_op{}(x)))
EXPR(Sigmoid, __float_as_uint(ops::sigmoid_op{}(x)))
EXPR(Relu, __float_as_uint(ops::relu_op{}(x)))
EXPR(Square, __float_as_uint(ops::square_op{}(x)))
EXPR(Tanh, __float_as_uint(ops::tanh_op{}(x)))
EXPR(Rsqrt, __float_as_uint(ops::rsqrt_op{}(x)))
EXPR(Sign, __float_as_uint(ops::sign_op{}(x)))
EXPR(Reciprocal, __float_as_uint(ops::reciprocal_op{}(x)))
EXPR(Floor, __float_as_uint(ops::floor_op{}(x)))
EXPR(Ceil, __float_as_uint(ops::ceil_op{}(x)))
EXPR(Round, __float_as_uint(ops::round_op{}(x)))
EXPR(Exp2, __float_as_uint(ops::exp2_op{}(x)))
EXPR(Log2, __float_as_uint(ops::log2_op{}(x)))
EXPR(Log10, __float_as_uint(ops::log10_op{}(x)))
EXPR(Log1p, __float_as_uint(ops::log1p_op{}(x)))
EXPR(Sin, __float_as_uint(ops::sin_op{}(x)))
EXPR(Cos, __float_as_uint(ops::cos_op{}(x)))
EXPR(Tan, __float_as_uint(ops::tan_op{}(x)))
EXPR(Asin, __float_as_uint(ops::asin_op{}(x)))
EXPR(Acos, __float_as_uint(ops::acos_op{}(x)))
EXPR(Atan, __float_as_uint(ops::atan_op{}(x)))
EXPR(Sinh, __float_as_uint(ops::sinh_op{}(x)))
EXPR(Cosh, __float_as_uint(ops::cosh_op{}(x)))
EXPR(Gelu, __float_as_uint(ops::gelu_op{}(x)))
EXPR(Swish, __float_as_uint(ops::swish_op{}(x)))
EXPR(Trunc, __float_as_uint(ops::trunc_op{}(x)))
EXPR(Add, __float_as_uint(ops::add_op{}(x, y)))
EXPR(Sub, __float_as_uint(ops::sub_op{}(x, y)))
EXPR(Mul, __float_as_uint(ops::mul_op{}(x, y)))
EXPR(Div, __float_as_uint(ops::div_op{}(x, y)))
EXPR(Mod, __float_as_uint(ops::mod_op{}(x, y)))
EXPR(Pow, __float_as_uint(ops::pow_op{}(x, y)))
EXPR(Min, __float_as_uint(ops::minimum_op{}(x, y)))
EXPR(Max, __float_as_uint(ops::maximum_op{}(x, y)))
EXPR(Atan2, __float_as_uint(ops::atan2_op{}(x, y)))
EXPR(IsNan, uint(ops::isnan_op{}(x)))
EXPR(IsInf, uint(ops::isinf_op{}(x)))
EXPR(IsFinite, uint(ops::isfinite_op{}(x)))
EXPR(Equal, uint(ops::equal_op{}(x, y)))
EXPR(NotEqual, uint(ops::not_equal_op{}(x, y)))
EXPR(Less, uint(ops::less_op{}(x, y)))
EXPR(LessEqual, uint(ops::less_equal_op{}(x, y)))
EXPR(Greater, uint(ops::greater_op{}(x, y)))
EXPR(GreaterEqual, uint(ops::greater_equal_op{}(x, y)))
EXPR(Fma, __float_as_uint(fmaf(x, y, z)))
EXPR(Clamp, ops::float_is_nan(x) ? a : __float_as_uint(ops::clamp_ternary_op<float>{}(x, y, z)))
EXPR(Select, a ? b : c)
EXPR(LogicalAnd, a != 0 && b != 0)
EXPR(LogicalOr, a != 0 || b != 0)
EXPR(LogicalXor, (a != 0) != (b != 0))
EXPR(LogicalNot, a == 0)
EXPR(BitAnd, a& b)
EXPR(BitOr, a | b)
EXPR(BitXor, a ^ b)
EXPR(BitNot, ~a)
EXPR(ShiftLeft, a << (b & 31))
EXPR(ShiftRight, a >> (b & 31))
EXPR(AddInt, a + b)
EXPR(SubInt, a - b)
EXPR(MulInt, a* b)
EXPR(IntDiv, b == 0 ? 0u : a == 0x80000000u && b == 0xffffffffu ? a
                                                                : uint(int(a) / int(b)))
EXPR(IntMod, b == 0 || (a == 0x80000000u && b == 0xffffffffu) ? 0u : uint(int(a) % int(b)))
EXPR(UIntDiv, b ? a / b : 0u)
EXPR(UIntMod, b ? a % b : 0u)
EXPR(CastFloat, __float_as_uint(float(int(a))))
EXPR(CastUnsignedFloat, __float_as_uint(float(a)))
EXPR(CastInt, uint(int(x)))
EXPR(CastUInt, uint(x))
EXPR(EqualInt, int(a) == int(b))
EXPR(NotEqualInt, int(a) != int(b))
EXPR(LessInt, int(a) < int(b))
EXPR(LessEqualInt, int(a) <= int(b))
EXPR(GreaterInt, int(a) > int(b))
EXPR(GreaterEqualInt, int(a) >= int(b))
EXPR(LessUInt, uint(a) < uint(b))
EXPR(LessEqualUInt, uint(a) <= uint(b))
EXPR(GreaterUInt, uint(a) > uint(b))
EXPR(GreaterEqualUInt, uint(a) >= uint(b))
EXPR(PackHalf, uint(__half_as_ushort(__float2half_rn(x))))
EXPR(UnpackHalf, __float_as_uint(__half2float(__ushort_as_half(a))))
#undef EXPR
