#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 LichtFeld Studio Authors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the node reference from lf.nodes.node_types(), or its JSON export.

Run in the application to include host-only nodes such as Object Info. With
--descriptors, pass an English node_types() export from that application.
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "docs/docs/development/node-graph/nodes"
EXAMPLES = ROOT / "docs/docs/development/node-graph/examples"
KINDS = ("enum", "string", "int", "float", "bool", "data")


def cell(value):
    if value is None:
        return "—"
    if isinstance(value, float):
        value = f"{value:.6g}"
    elif not isinstance(value, str):
        value = json.dumps(value, ensure_ascii=False)
    return value.replace("|", "\\|").replace("\n", "<br/>")


def render_node(descriptor, examples=EXAMPLES):
    node_id = descriptor["id"]
    lines = ["<!-- Generated by tools/generate_node_reference.py; edit node descriptors, not this page. -->",
             f"# {descriptor['label']}", "", descriptor["description"], "",
             f"`{node_id}` · {descriptor['category']}", "", "## How to use", ""]
    # CommonMark hard breaks without trailing spaces (git diff --check).
    help_lines = descriptor.get("help", "").splitlines()
    lines.extend(line + ("\\" if index + 1 < len(help_lines) else "")
                 for index, line in enumerate(help_lines))
    for collection, title in (("inputs", "Inputs"), ("outputs", "Outputs"), ("properties", "Settings")):
        declarations = descriptor.get(collection, [])
        if not declarations:
            continue
        lines.extend(["", f"## {title}", "",
                      "| Name | Identifier | Type | Default | Range / choices | Description |",
                      "| --- | --- | --- | --- | --- | --- |"])
        for declaration in declarations:
            kind = declaration.get("type", declaration.get("kind", ""))
            if isinstance(kind, int):
                kind = KINDS[kind]
            bounds = []
            if declaration.get("min") is not None:
                bounds.append("min " + cell(declaration["min"]))
            if declaration.get("max") is not None:
                bounds.append("max " + cell(declaration["max"]))
            if declaration.get("step") is not None:
                bounds.append("step " + cell(declaration["step"]))
            for bound in ("soft_min", "soft_max"):
                if declaration.get(bound) is not None:
                    bounds.append(bound.replace("_", " ") + " " + cell(declaration[bound]))
            bounds.extend(declaration.get("items", []))
            if declaration.get("field"):
                bounds.append("accepts per-element values")
            if declaration.get("multi_input"):
                bounds.append("accepts multiple links")
            values = [declaration["label"], f"`{declaration['identifier']}`", kind,
                      declaration.get("default"), "; ".join(bounds) or "—", declaration.get("description", "")]
            lines.append("| " + " | ".join(cell(value) for value in values) + " |")
    lines.extend(["", "## Used in examples", ""])
    matches = []
    for path in sorted(examples.glob("*.py")):
        if f'"{node_id}"' in path.read_text(encoding="utf-8") or f"'{node_id}'" in path.read_text(encoding="utf-8"):
            matches.append(f"- [{path.stem}](../examples/{path.name})")
    lines.extend(matches or ["No shipped example currently uses this node."])
    return "\n".join(lines) + "\n"


def render_index(descriptors):
    lines = ["<!-- Generated by tools/generate_node_reference.py. -->", "# Node reference", "",
             "Select a node in the editor for its controls and How to use guidance.", ""]
    category = None
    for node in sorted(descriptors, key=lambda node: (node["category"], node["label"], node["id"])):
        if node["category"] != category:
            category = node["category"]
            lines.extend([f"## {category}", ""])
        lines.extend([f"- [{node['label']}]({node['id']}.md) — {node['description']}", ""])
    return "\n".join(lines)


def generate(descriptors=None, destination=DESTINATION, check=False):
    if descriptors is None:
        import lichtfeld as lf
        descriptors = lf.nodes.node_types()
    descriptors = [node for node in descriptors if node["id"].startswith("lfs.")]
    pages = {node["id"] + ".md": render_node(node) for node in descriptors}
    # Outside the application host-only types such as Object Info are not
    # registered; keep their existing pages listed in the index.
    known = {node["id"] for node in descriptors}
    indexed = list(descriptors)
    for page in destination.glob("lfs.*.md"):
        if page.stem not in known:
            lines = page.read_text(encoding="utf-8").splitlines()
            indexed.append(dict(id=page.stem, label=lines[1][2:], description=lines[3],
                                category=lines[5].split(" · ", 1)[1]))
    pages["index.md"] = render_index(indexed)
    stale = []
    for name, text in pages.items():
        path = destination / name
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            destination.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if stale:
        raise ValueError("Node reference is stale; regenerate: " + ", ".join(stale))
    return len(pages)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--descriptors", type=Path, help="English lf.nodes.node_types() JSON export, including host-only types")
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    data = json.loads(options.descriptors.read_text(encoding="utf-8")) if options.descriptors else None
    print(f"{generate(data, check=options.check)} node reference pages {'checked' if options.check else 'written'}")
