# SPDX-FileCopyrightText: 2026 LichtFeld Studio Authors
# SPDX-License-Identifier: GPL-3.0-or-later

# One deliberate FFmpeg provider. Keep package debug/optimized qualifiers and
# transitive dependencies intact, but include all public API objects from each
# static FFmpeg archive so existing Studio users can resolve their calls here.
function(lfs_link_ffmpeg_provider target)
    set(_libraries)
    set(_exports "EXPORTS\n")
    set(_exported_names)
    foreach(_library IN LISTS FFMPEG_LIBRARIES)
        get_filename_component(_name "${_library}" NAME)
        if(_name MATCHES "^(lib)?(avcodec|avformat|avutil|avfilter|avdevice|swscale|swresample)(d)?\\.(a|lib)$")
            set(_component "${CMAKE_MATCH_2}")
            set(_dlls)
            if(WIN32)
                get_filename_component(_lib_dir "${_library}" DIRECTORY)
                file(GLOB _dlls "${_lib_dir}/../bin/${_component}-*.dll")
            endif()
            if(_dlls)
                # Windows' existing package uses shared FFmpeg. Forward its API
                # through this DLL instead of importing it independently in every
                # consumer. The loader retains one underlying implementation.
                list(LENGTH _dlls _dll_count)
                if(NOT _dll_count EQUAL 1)
                    message(FATAL_ERROR "Ambiguous FFmpeg DLL for ${_library}: ${_dlls}")
                endif()
                list(GET _dlls 0 _dll)
                get_filename_component(_dll_name "${_dll}" NAME_WE)
                execute_process(COMMAND "${CMAKE_LINKER}" /dump /exports "${_dll}"
                    RESULT_VARIABLE _status OUTPUT_VARIABLE _symbols ERROR_VARIABLE _error)
                if(NOT _status EQUAL 0)
                    message(FATAL_ERROR "Cannot inspect FFmpeg exports: ${_error}")
                endif()
                string(REPLACE "\n" ";" _lines "${_symbols}")
                foreach(_line IN LISTS _lines)
                    if(_line MATCHES "^[ \t]+[0-9]+[ \t]+[0-9A-Fa-f]+[ \t]+[0-9A-Fa-f]+[ \t]+((av|avcodec|avformat|avutil|avfilter|avdevice|avio|swscale|swresample|sws|swr)_[A-Za-z0-9_]+)")
                        set(_symbol "${CMAKE_MATCH_1}")
                        if(NOT _symbol IN_LIST _exported_names)
                            list(APPEND _exported_names "${_symbol}")
                            string(APPEND _exports "    ${_symbol}=${_dll_name}.${_symbol}\n")
                        endif()
                    endif()
                endforeach()
                list(APPEND _libraries "${_library}")
            else()
                list(APPEND _libraries "$<LINK_LIBRARY:WHOLE_ARCHIVE,${_library}>")
                if(WIN32)
                    execute_process(COMMAND "${CMAKE_LINKER}" /dump /linkermember:1 "${_library}"
                        RESULT_VARIABLE _status OUTPUT_VARIABLE _symbols ERROR_VARIABLE _error)
                    if(NOT _status EQUAL 0)
                        message(FATAL_ERROR "Cannot inspect FFmpeg archive: ${_error}")
                    endif()
                    string(REPLACE "\n" ";" _lines "${_symbols}")
                    foreach(_line IN LISTS _lines)
                        if(_line MATCHES "^[ \t]+[0-9A-Fa-f]+[ \t]+((av|avcodec|avformat|avutil|avfilter|avdevice|avio|swscale|swresample|sws|swr)_[A-Za-z0-9_]+)[ \r]*$")
                            set(_symbol "${CMAKE_MATCH_1}")
                            if(NOT _symbol IN_LIST _exported_names)
                                list(APPEND _exported_names "${_symbol}")
                                string(APPEND _exports "    ${_symbol}\n")
                            endif()
                        endif()
                    endforeach()
                endif()
            endif()
        else()
            list(APPEND _libraries "${_library}")
        endif()
    endforeach()
    target_link_libraries(${target} PRIVATE ${_libraries})
    if(WIN32)
        if(NOT _exported_names)
            message(FATAL_ERROR "No public FFmpeg exports found for ${target}")
        endif()
        set(_export_file "${CMAKE_CURRENT_BINARY_DIR}/ffmpeg-provider.def")
        file(CONFIGURE OUTPUT "${_export_file}" CONTENT "${_exports}" @ONLY)
        target_sources(${target} PRIVATE "${_export_file}")
    elseif(APPLE)
        set(_export_file "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../src/media/ffmpeg-provider.exports")
        target_link_options(${target} PRIVATE "LINKER:-exported_symbols_list,${_export_file}")
        set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${_export_file}")
    else()
        set(_export_file "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../src/media/ffmpeg-provider.map")
        target_link_options(${target} PRIVATE "LINKER:--version-script=${_export_file}")
        set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${_export_file}")
    endif()
endfunction()
