# SPDX-FileCopyrightText: 2026 LichtFeld Studio Authors
# SPDX-License-Identifier: GPL-3.0-or-later
include_guard(GLOBAL)

# Custom nvcc commands must follow the same architecture selection as CMake's
# CUDA targets: an unsuffixed architecture emits both SASS and PTX.
function(lfs_gpu_program_cuda_flags output)
    set(architectures)
    foreach(architecture IN LISTS CMAKE_CUDA_ARCHITECTURES)
        if(architecture STREQUAL "native")
            list(APPEND architectures ${CMAKE_CUDA_ARCHITECTURES_NATIVE})
        elseif(architecture STREQUAL "all")
            list(APPEND architectures ${CMAKE_CUDA_ARCHITECTURES_ALL})
        elseif(architecture STREQUAL "all-major")
            list(APPEND architectures ${CMAKE_CUDA_ARCHITECTURES_ALL_MAJOR})
        else()
            list(APPEND architectures "${architecture}")
        endif()
    endforeach()
    if(NOT architectures)
        message(FATAL_ERROR "CUDA GPU programs require resolved CUDA architectures")
    endif()
    set(flags)
    foreach(architecture IN LISTS architectures)
        if(NOT architecture MATCHES "^([0-9]+[a-z]?)(-(real|virtual))?$")
            message(FATAL_ERROR "Unsupported CUDA GPU program architecture: ${architecture}")
        endif()
        set(sm "${CMAKE_MATCH_1}")
        set(kind "${CMAKE_MATCH_3}")
        set(codes)
        if(NOT kind STREQUAL "virtual")
            list(APPEND codes "sm_${sm}")
        endif()
        if(NOT kind STREQUAL "real")
            list(APPEND codes "compute_${sm}")
        endif()
        list(JOIN codes "," codes)
        list(APPEND flags "--generate-code=arch=compute_${sm},code=[${codes}]")
    endforeach()
    list(REMOVE_DUPLICATES flags)
    set(${output} "${flags}" PARENT_SCOPE)
endfunction()
