# Verify every selected source file, including nested and newly added resources.
function(lfs_verify_installed_tree source destination pattern exclude)
    if(NOT IS_DIRECTORY "${source}")
        message(FATAL_ERROR "Missing source inventory: ${source}")
    endif()
    file(GLOB_RECURSE _files LIST_DIRECTORIES FALSE RELATIVE "${source}" "${source}/${pattern}")
    set(_count 0)
    foreach(_relative IN LISTS _files)
        if(NOT "${exclude}" STREQUAL "" AND _relative MATCHES "${exclude}")
            continue()
        endif()
        if(NOT EXISTS "${destination}/${_relative}" OR IS_DIRECTORY "${destination}/${_relative}")
            message(FATAL_ERROR "Missing bundled resource: ${destination}/${_relative}")
        endif()
        math(EXPR _count "${_count} + 1")
    endforeach()
    if(_count EQUAL 0)
        message(FATAL_ERROR "Empty source inventory: ${source} (${pattern})")
    endif()
    message(STATUS "Verified ${_count} resources from ${source}")
endfunction()
